https://anfavea.com.br/site/edicoes-em-excel/

In [1]:
import datetime
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter

In [2]:
pd.set_option('display.max_columns', None)

In [4]:
df_anfavea = pd.read_excel('../dados/silver/anfavea_producao_veiculos.xlsx', engine='openpyxl')

In [5]:
df_anfavea.head()

,Date,AUTOVEÍCULOS TOTAL_Produção,AUTOMÓVEIS_Produção,COMERCIAIS LEVES_Produção,CAMINHÕES_Produção,ÔNIBUS_Produção,producao_total
0,2013-01-01,291884,237700,38430,12622,3132,583768
1,2013-02-01,242072,191832,33564,13664,3012,484144
2,2013-03-01,329103,265001,43782,16533,3787,658206
3,2013-04-01,352328,278924,51538,18034,3832,704656
4,2013-05-01,344556,275799,48491,16378,3888,689112

In [6]:
index = 0
lista_blocos = ['AUTOVEÍCULOS TOTAL', 'AUTOMÓVEIS', 'COMERCIAIS LEVES', 'CAMINHÕES', 'ÔNIBUS']
lista_variaveis = ['Emplacamento Total', 'Emplacamento Nacionais', 'Emplacamento Importados', 'Produção', 'Exportação']
for nome in df_anfavea.columns:
    if 'Unnamed: 0' in nome:
        df_anfavea.rename(columns={'Unnamed: 0':'Date'}, inplace=True)
    else:
        if 'Unnamed' not in nome:
            bloco = nome
        df_anfavea.rename(columns={nome:f'{bloco}_{lista_variaveis[index]}'}, inplace=True)
        index += 1
    if index == 5:
        index = 0
df_anfavea.drop(0, axis=0, inplace=True)

In [7]:
df_anfavea = df_anfavea[(df_anfavea['Date'] > pd.Timestamp(2012, 12, 31)) & (df_anfavea['Date'] < pd.Timestamp(2026, 3, 1))].copy()
df_anfavea.reset_index(drop=True, inplace=True)

KeyError: 'Date'

In [8]:
df_anfavea.head()

,Date_Emplacamento Total,AUTOVEÍCULOS TOTAL_Produção_Emplacamento Nacionais,AUTOMÓVEIS_Produção_Emplacamento Importados,COMERCIAIS LEVES_Produção_Produção,CAMINHÕES_Produção_Exportação,ÔNIBUS_Produção_Emplacamento Total,producao_total_Emplacamento Nacionais
1,2013-02-01,242072,191832,33564,13664,3012,484144
2,2013-03-01,329103,265001,43782,16533,3787,658206
3,2013-04-01,352328,278924,51538,18034,3832,704656
4,2013-05-01,344556,275799,48491,16378,3888,689112
5,2013-06-01,323853,257861,45781,16136,4075,647706

In [8]:
colunas_producao = []

for column in df_anfavea.columns:
    if 'Produção' in column:
        colunas_producao.append(column)

producao_total = df_anfavea[colunas_producao].sum(axis=1)

df_anfavea = df_anfavea[['Date']+colunas_producao].copy()
df_anfavea['producao_total'] = producao_total

In [9]:
df_anfavea

,Date_Emplacamento Total,AUTOVEÍCULOS TOTAL_Produção_Emplacamento Nacionais,AUTOMÓVEIS_Produção_Emplacamento Importados,COMERCIAIS LEVES_Produção_Produção,CAMINHÕES_Produção_Exportação,ÔNIBUS_Produção_Emplacamento Total,producao_total_Emplacamento Nacionais
1,2013-02-01,242072,191832,33564,13664,3012,484144
2,2013-03-01,329103,265001,43782,16533,3787,658206
3,2013-04-01,352328,278924,51538,18034,3832,704656
4,2013-05-01,344556,275799,48491,16378,3888,689112
5,2013-06-01,323853,257861,45781,16136,4075,647706
...,...,...,...,...,...,...,...
156,2026-01-01,163672,124193,30782,6813,1884,327344
157,2026-02-01,207028,154946,41499,7797,2786,414056
158,2026-03-01,263608,199116,50214,11133,3145,527216
159,2026-04-01,238550,182990,42792,9673,3095,477100
160,2026-05-01,253519,201184,38872,10488,2975,507038

In [ ]:
#df_anfavea.to_excel('./Dados Silver/anfavea_producao_veiculos.xlsx', index=False, engine='openpyxl')