In [1]:
import os
import pandas as pd

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
caminho_principal = './dados/silver/'
lista_arquivos = os.listdir(caminho_principal)
#primeiro_arquivo = lista_arquivos[1]
arquivo_variavel_alvo = 'Performance.xlsx'
#lista_arquivos.remove(primeiro_arquivo)
lista_arquivos.remove('Performance.xlsx')
lista_arquivos.remove('ipea_fbc.xlsx')
lista_arquivos.remove('bc_sgs_projecao_selic.xlsx')

In [4]:
lista_arquivos

['anfavea_producao_veiculos.xlsx',
 'bc_sgs_ipca_pib.xlsx',
 'bc_sgs_operacoes_credito_industria.xlsx',
 'gov_br_cno.xlsx',
 'ipea_cambio.xlsx',
 'ipea_selic.xlsx',
 'sidra_ipp.xlsx',
 'sidra_pim_pf.xlsx',
 'sidra_pnad_ocupacao.xlsx',
 'sidra_sinapi_m2.xlsx']

In [5]:
for item in lista_arquivos:
    if 'm2' in item:
        print(item)
        nome_arquivo = item

sidra_sinapi_m2.xlsx

In [6]:
df_custo_m2 = pd.read_excel(caminho_principal+nome_arquivo, engine='openpyxl')
df_custo_m2

          Date  custo_projeto_m2
0   2014-03-01        1789677.76
1   2014-04-01        1795689.30
2   2014-05-01        1809898.74
3   2014-06-01        1822703.31
4   2014-07-01        1835144.66
..         ...               ...
139 2025-10-01        3906633.17
140 2025-11-01        3917134.22
141 2025-12-01        3929314.11
142 2026-01-01        3944742.89
143 2026-02-01        3955566.79

[144 rows x 2 columns]

In [7]:
for item in lista_arquivos:
    if 'credito' in item:
        print(item)
        nome_arquivo = item

bc_sgs_operacoes_credito_industria.xlsx

In [8]:
df_operacoes_credito = pd.read_excel(caminho_principal+nome_arquivo, engine='openpyxl')
df_operacoes_credito

,Date,operacoes_credito_industria_construcao,operacoes_credito_industria_infraestrutura,operacoes_credito_industria_metalurgia_siderurgia
0,2012-01-01,77754,21887,47118
1,2012-02-01,78890,22346,47431
2,2012-03-01,80919,22620,47472
3,2012-04-01,82271,23106,47523
4,2012-05-01,84393,23735,47347
...,...,...,...,...
164,2025-09-01,156706,35396,54928
165,2025-10-01,158600,36032,54526
166,2025-11-01,160270,35705,54036
167,2025-12-01,163044,36253,57662
168,2026-01-01,160982,35690,55570

In [9]:
for item in lista_arquivos:
    if 'cno' in item:
        print(item)
        nome_arquivo = item

gov_br_cno.xlsx

In [10]:
df_cno = pd.read_excel(caminho_principal+nome_arquivo, engine='openpyxl')
df_cno

,Date,Outra,km,kva,kw,m2,m3
0,2013-01-01,2.265353e+05,1318.93,0.00,0.00,6121799.45,57915.94
1,2013-02-01,2.375263e+06,35356.44,300.00,0.00,3546150.38,202427.96
2,2013-03-01,3.755053e+04,151.27,0.00,143845.00,3527108.38,296.10
3,2013-04-01,8.660776e+07,18317.29,0.00,56.24,4138050.85,21194.45
4,2013-05-01,6.161909e+05,1561.29,0.00,117.06,4466101.19,48913.61
...,...,...,...,...,...,...,...
154,2025-11-01,1.042772e+09,143391.73,180106.13,22984.50,24509257.09,18664097.40
155,2025-12-01,2.507515e+08,22815.14,698677.01,18367.82,20418478.13,2158827.08
156,2026-01-01,2.489311e+08,52556.79,15216.61,4396988.30,18954998.25,8361964.22
157,2026-02-01,4.361724e+08,58970.33,58168.70,204111.00,11468385.49,2865195.13
158,2026-03-01,2.451151e+06,102.66,26669.00,103200.00,3302580.18,30869.95

In [11]:
for item in lista_arquivos:
    if 'pim_pf' in item:
        print(item)
        nome_arquivo = item

sidra_pim_pf.xlsx

In [12]:
df_pim_pf = pd.read_excel(caminho_principal+nome_arquivo, engine='openpyxl')
df_pim_pf

,Date,3.24 Metalurgia,3.28 Fabricação de máquinas e equipamentos,"3.29 Fabricação de veículos automotores, reboques e carrocerias","3.30 Fabricação de outros equipamentos de transporte, exceto veículos automotores"
0,2014-02-01,1544.78521,708.69168,1000.42146,1304.58480
1,2014-03-01,1627.26879,648.56838,932.29050,1289.01576
2,2014-04-01,1568.60663,601.80655,958.02687,1329.35659
3,2014-05-01,1598.92700,660.43780,967.89891,1304.52774
4,2014-06-01,1445.08987,536.25142,774.63730,1163.22075
...,...,...,...,...,...
139,2025-09-01,1259.06857,948.59660,974.53909,464.10337
140,2025-10-01,1340.00342,947.33806,1040.15079,479.55698
141,2025-11-01,1298.53131,812.54500,918.23883,438.35117
142,2025-12-01,1005.39987,856.40874,706.36965,378.81819
143,2026-01-01,1273.83386,714.21230,664.70118,439.27299

In [13]:
for item in lista_arquivos:
    if 'pib' in item:
        print(item)
        nome_arquivo = item

bc_sgs_ipca_pib.xlsx

In [14]:
df_bc_pib = pd.read_excel(caminho_principal+nome_arquivo, engine='openpyxl')
df_bc_pib

          Date  IPCA  PIB_mensal
0   2013-01-01  0.86    408895.0
1   2013-02-01  0.60    398087.4
2   2013-03-01  0.47    434631.2
3   2013-04-01  0.55    446508.1
4   2013-05-01  0.37    441322.0
..         ...   ...         ...
153 2025-10-01  0.09   1107951.1
154 2025-11-01  0.18   1084709.5
155 2025-12-01  0.33   1085129.6
156 2026-01-01  0.33   1023703.2
157 2026-02-01  0.70   1042272.6

[158 rows x 3 columns]

In [15]:
for item in lista_arquivos:
    if 'anfavea' in item:
        print(item)
        nome_arquivo = item

anfavea_producao_veiculos.xlsx

In [16]:
df_anfavea = pd.read_excel(caminho_principal+nome_arquivo, engine='openpyxl')
df_anfavea

,Date,AUTOVEÍCULOS TOTAL_Produção,AUTOMÓVEIS_Produção,COMERCIAIS LEVES_Produção,CAMINHÕES_Produção,ÔNIBUS_Produção,producao_total
0,2013-01-01,291884,237700,38430,12622,3132,583768
1,2013-02-01,242072,191832,33564,13664,3012,484144
2,2013-03-01,329103,265001,43782,16533,3787,658206
3,2013-04-01,352328,278924,51538,18034,3832,704656
4,2013-05-01,344556,275799,48491,16378,3888,689112
...,...,...,...,...,...,...,...
153,2025-10-01,247770,184841,50635,10160,2134,495540
154,2025-11-01,219058,164868,43263,9601,1326,438116
155,2025-12-01,184474,139947,38103,5723,701,368948
156,2026-01-01,163606,124193,30782,6811,1820,327212
157,2026-02-01,204345,152346,41499,7797,2703,408690

In [17]:
for item in lista_arquivos:
    if 'cambio' in item:
        print(item)
        nome_arquivo = item

ipea_cambio.xlsx

In [18]:
df_ipea_cambio = pd.read_excel(caminho_principal+nome_arquivo, engine='openpyxl')
df_ipea_cambio

          Date  valor_cambio_reais
0   2013-01-01            1.440984
1   2013-02-01            1.268150
2   2013-03-01            1.278884
3   2013-04-01            1.467863
4   2013-05-01            1.378052
..         ...                 ...
154 2025-11-01            5.340253
155 2025-12-01            5.452482
156 2026-01-01            5.337419
157 2026-02-01            5.200011
158 2026-03-01            5.225609

[159 rows x 2 columns]

In [19]:
for item in lista_arquivos:
    if 'fbc' in item:
        print(item)
        nome_arquivo = item

In [20]:
#df_ipea_fbc = pd.read_excel(caminho_principal+nome_arquivo, engine='openpyxl')
#df_ipea_fbc

In [21]:
for item in lista_arquivos:
    if 'ipp' in item:
        print(item)
        nome_arquivo = item

sidra_ipp.xlsx

In [22]:
df_sidra_ipp = pd.read_excel(caminho_principal+nome_arquivo, engine='openpyxl')
df_sidra_ipp

,Date,24 METALURGIA,"25 FABRICAÇÃO DE PRODUTOS DE METAL, EXCETO MÁQUINAS E EQUIPAMENTOS","27 FABRICAÇÃO DE MÁQUINAS, APARELHOS E MATERIAIS ELÉTRICOS",28 FABRICAÇÃO DE MÁQUINAS E EQUIPAMENTOS,"29 FABRICAÇÃO DE VEÍCULOS AUTOMOTORES, REBOQUES E CARROCERIAS","30 FABRICAÇÃO DE OUTROS EQUIPAMENTOS DE TRANSPORTE, EXCETO VEÍCULOS AUTOMOTORES"
0,2014-02-01,70.98218,77.27480,75.22319,81.86551,77.51273,64.23011
1,2014-03-01,70.78954,77.04495,75.58447,81.12523,77.39578,63.57421
2,2014-04-01,70.52026,77.34009,75.14999,80.78319,77.59273,61.84009
3,2014-05-01,70.72374,77.24797,77.04906,80.80671,77.61381,61.80048
4,2014-06-01,71.51497,77.06881,76.65715,81.08439,77.66284,62.19166
...,...,...,...,...,...,...,...
139,2025-09-01,170.35175,168.22590,168.92221,183.78253,159.99832,166.67084
140,2025-10-01,173.44078,167.95270,169.73408,184.22017,160.12022,167.94769
141,2025-11-01,172.85646,168.44572,172.32235,183.32387,160.50728,167.84633
142,2025-12-01,176.73024,168.95391,175.63531,181.80880,161.10558,170.77303
143,2026-01-01,181.55805,171.55540,175.87805,182.11315,161.49538,170.09721

In [23]:
for item in lista_arquivos:
    if 'projecao' in item:
        print(item)
        nome_arquivo = item

In [24]:
#df_bc_projecao_selic = pd.read_excel(caminho_principal+nome_arquivo, engine='openpyxl')
#df_bc_projecao_selic

In [25]:
for item in lista_arquivos:
    if 'pnad' in item:
        print(item)
        nome_arquivo = item

sidra_pnad_ocupacao.xlsx

In [26]:
df_pnad_ocupacao = pd.read_excel(caminho_principal+nome_arquivo, engine='openpyxl')
df_pnad_ocupacao

,"Nível da ocupação, na semana de referência, das pessoas de 14 anos ou mais de idade",Date
0,58.2,2013-08-01
1,58.2,2013-09-01
2,58.3,2013-10-01
3,58.5,2013-11-01
4,58.5,2013-12-01
...,...,...
145,58.7,2025-09-01
146,58.8,2025-10-01
147,59.0,2025-11-01
148,58.9,2025-12-01
149,58.7,2026-01-01

In [27]:
for item in lista_arquivos:
    if 'ipea_selic' in item:
        print(item)
        nome_arquivo = item

ipea_selic.xlsx

In [28]:
df_ipea_selic = pd.read_excel(caminho_principal+nome_arquivo, engine='openpyxl')
df_ipea_selic

          Date  taxa_selic_aa
0   2013-01-01       7.442417
1   2013-02-01       6.041083
2   2013-03-01       6.803356
3   2013-04-01       7.570649
4   2013-05-01       7.442417
..         ...            ...
154 2025-11-01      13.353730
155 2025-12-01      15.663411
156 2026-01-01      14.843349
157 2026-02-01      12.682503
158 2026-03-01       7.570649

[159 rows x 2 columns]

**Juntar as tabelas**

In [29]:
df_final = df_custo_m2.merge(df_operacoes_credito, on='Date').copy()
df_final

,Date,custo_projeto_m2,operacoes_credito_industria_construcao,operacoes_credito_industria_infraestrutura,operacoes_credito_industria_metalurgia_siderurgia
0,2014-03-01,1789677.76,110130,27467,49832
1,2014-04-01,1795689.30,111799,27566,49751
2,2014-05-01,1809898.74,113783,28389,49331
3,2014-06-01,1822703.31,114449,28853,49127
4,2014-07-01,1835144.66,114323,29287,48528
...,...,...,...,...,...
138,2025-09-01,3892811.47,156706,35396,54928
139,2025-10-01,3906633.17,158600,36032,54526
140,2025-11-01,3917134.22,160270,35705,54036
141,2025-12-01,3929314.11,163044,36253,57662
142,2026-01-01,3944742.89,160982,35690,55570

In [30]:
df_final.shape

(143, 5)

In [31]:
df_final = df_final.merge(df_cno, on='Date').copy()
df_final

,Date,custo_projeto_m2,operacoes_credito_industria_construcao,operacoes_credito_industria_infraestrutura,operacoes_credito_industria_metalurgia_siderurgia,Outra,km,kva,kw,m2,m3
0,2014-03-01,1789677.76,110130,27467,49832,1.281451e+08,27611.11,500.00,51050.17,3.876616e+06,341809.82
1,2014-04-01,1795689.30,111799,27566,49751,2.380034e+06,63868.05,0.00,56000.00,5.135527e+06,30289.10
2,2014-05-01,1809898.74,113783,28389,49331,2.394161e+06,79957.55,0.00,0.00,5.659767e+06,308819.95
3,2014-06-01,1822703.31,114449,28853,49127,1.583328e+07,206138.84,0.00,36.77,5.696066e+06,120894.28
4,2014-07-01,1835144.66,114323,29287,48528,1.925414e+07,155870.07,300231.00,644.80,7.271089e+06,60804.87
...,...,...,...,...,...,...,...,...,...,...,...
138,2025-09-01,3892811.47,156706,35396,54928,8.781352e+08,248922.88,353990.51,4995478.81,5.824206e+08,4444577.04
139,2025-10-01,3906633.17,158600,36032,54526,2.600877e+08,4833965.89,1845913.56,40506.05,3.993856e+07,6033857.29
140,2025-11-01,3917134.22,160270,35705,54036,1.042772e+09,143391.73,180106.13,22984.50,2.450926e+07,18664097.40
141,2025-12-01,3929314.11,163044,36253,57662,2.507515e+08,22815.14,698677.01,18367.82,2.041848e+07,2158827.08
142,2026-01-01,3944742.89,160982,35690,55570,2.489311e+08,52556.79,15216.61,4396988.30,1.895500e+07,8361964.22

In [32]:
df_final.shape

(143, 11)

In [33]:
df_final = df_final.merge(df_pim_pf, on='Date').copy()
df_final

,Date,custo_projeto_m2,operacoes_credito_industria_construcao,operacoes_credito_industria_infraestrutura,operacoes_credito_industria_metalurgia_siderurgia,Outra,km,kva,kw,m2,m3,3.24 Metalurgia,3.28 Fabricação de máquinas e equipamentos,"3.29 Fabricação de veículos automotores, reboques e carrocerias","3.30 Fabricação de outros equipamentos de transporte, exceto veículos automotores"
0,2014-03-01,1789677.76,110130,27467,49832,1.281451e+08,27611.11,500.00,51050.17,3.876616e+06,341809.82,1627.26879,648.56838,932.29050,1289.01576
1,2014-04-01,1795689.30,111799,27566,49751,2.380034e+06,63868.05,0.00,56000.00,5.135527e+06,30289.10,1568.60663,601.80655,958.02687,1329.35659
2,2014-05-01,1809898.74,113783,28389,49331,2.394161e+06,79957.55,0.00,0.00,5.659767e+06,308819.95,1598.92700,660.43780,967.89891,1304.52774
3,2014-06-01,1822703.31,114449,28853,49127,1.583328e+07,206138.84,0.00,36.77,5.696066e+06,120894.28,1445.08987,536.25142,774.63730,1163.22075
4,2014-07-01,1835144.66,114323,29287,48528,1.925414e+07,155870.07,300231.00,644.80,7.271089e+06,60804.87,1559.18983,786.14218,911.41471,1335.39708
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,2025-09-01,3892811.47,156706,35396,54928,8.781352e+08,248922.88,353990.51,4995478.81,5.824206e+08,4444577.04,1259.06857,948.59660,974.53909,464.10337
139,2025-10-01,3906633.17,158600,36032,54526,2.600877e+08,4833965.89,1845913.56,40506.05,3.993856e+07,6033857.29,1340.00342,947.33806,1040.15079,479.55698
140,2025-11-01,3917134.22,160270,35705,54036,1.042772e+09,143391.73,180106.13,22984.50,2.450926e+07,18664097.40,1298.53131,812.54500,918.23883,438.35117
141,2025-12-01,3929314.11,163044,36253,57662,2.507515e+08,22815.14,698677.01,18367.82,2.041848e+07,2158827.08,1005.39987,856.40874,706.36965,378.81819
142,2026-01-01,3944742.89,160982,35690,55570,2.489311e+08,52556.79,15216.61,4396988.30,1.895500e+07,8361964.22,1273.83386,714.21230,664.70118,439.27299

In [34]:
df_final.shape

(143, 15)

In [35]:
df_final = df_final.merge(df_bc_pib, on='Date').copy()
df_final

,Date,custo_projeto_m2,operacoes_credito_industria_construcao,operacoes_credito_industria_infraestrutura,operacoes_credito_industria_metalurgia_siderurgia,Outra,km,kva,kw,m2,m3,3.24 Metalurgia,3.28 Fabricação de máquinas e equipamentos,"3.29 Fabricação de veículos automotores, reboques e carrocerias","3.30 Fabricação de outros equipamentos de transporte, exceto veículos automotores",IPCA,PIB_mensal
0,2014-03-01,1789677.76,110130,27467,49832,1.281451e+08,27611.11,500.00,51050.17,3.876616e+06,341809.82,1627.26879,648.56838,932.29050,1289.01576,0.92,477202.9
1,2014-04-01,1795689.30,111799,27566,49751,2.380034e+06,63868.05,0.00,56000.00,5.135527e+06,30289.10,1568.60663,601.80655,958.02687,1329.35659,0.67,479729.8
2,2014-05-01,1809898.74,113783,28389,49331,2.394161e+06,79957.55,0.00,0.00,5.659767e+06,308819.95,1598.92700,660.43780,967.89891,1304.52774,0.46,481273.4
3,2014-06-01,1822703.31,114449,28853,49127,1.583328e+07,206138.84,0.00,36.77,5.696066e+06,120894.28,1445.08987,536.25142,774.63730,1163.22075,0.40,461318.6
4,2014-07-01,1835144.66,114323,29287,48528,1.925414e+07,155870.07,300231.00,644.80,7.271089e+06,60804.87,1559.18983,786.14218,911.41471,1335.39708,0.01,486872.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,2025-09-01,3892811.47,156706,35396,54928,8.781352e+08,248922.88,353990.51,4995478.81,5.824206e+08,4444577.04,1259.06857,948.59660,974.53909,464.10337,0.48,1074352.8
139,2025-10-01,3906633.17,158600,36032,54526,2.600877e+08,4833965.89,1845913.56,40506.05,3.993856e+07,6033857.29,1340.00342,947.33806,1040.15079,479.55698,0.09,1107951.1
140,2025-11-01,3917134.22,160270,35705,54036,1.042772e+09,143391.73,180106.13,22984.50,2.450926e+07,18664097.40,1298.53131,812.54500,918.23883,438.35117,0.18,1084709.5
141,2025-12-01,3929314.11,163044,36253,57662,2.507515e+08,22815.14,698677.01,18367.82,2.041848e+07,2158827.08,1005.39987,856.40874,706.36965,378.81819,0.33,1085129.6
142,2026-01-01,3944742.89,160982,35690,55570,2.489311e+08,52556.79,15216.61,4396988.30,1.895500e+07,8361964.22,1273.83386,714.21230,664.70118,439.27299,0.33,1023703.2

In [36]:
df_final.shape

(143, 17)

In [37]:
df_final = df_final.merge(df_anfavea, on='Date').copy()
df_final

,Date,custo_projeto_m2,operacoes_credito_industria_construcao,operacoes_credito_industria_infraestrutura,operacoes_credito_industria_metalurgia_siderurgia,Outra,km,kva,kw,m2,m3,3.24 Metalurgia,3.28 Fabricação de máquinas e equipamentos,"3.29 Fabricação de veículos automotores, reboques e carrocerias","3.30 Fabricação de outros equipamentos de transporte, exceto veículos automotores",IPCA,PIB_mensal,AUTOVEÍCULOS TOTAL_Produção,AUTOMÓVEIS_Produção,COMERCIAIS LEVES_Produção,CAMINHÕES_Produção,ÔNIBUS_Produção,producao_total
0,2014-03-01,1789677.76,110130,27467,49832,1.281451e+08,27611.11,500.00,51050.17,3.876616e+06,341809.82,1627.26879,648.56838,932.29050,1289.01576,0.92,477202.9,272754,218999,36211,13844,3700,545508
1,2014-04-01,1795689.30,111799,27566,49751,2.380034e+06,63868.05,0.00,56000.00,5.135527e+06,30289.10,1568.60663,601.80655,958.02687,1329.35659,0.67,479729.8,277091,218831,42551,12314,3395,554182
2,2014-05-01,1809898.74,113783,28389,49331,2.394161e+06,79957.55,0.00,0.00,5.659767e+06,308819.95,1598.92700,660.43780,967.89891,1304.52774,0.46,481273.4,281355,225128,40144,12695,3388,562710
3,2014-06-01,1822703.31,114449,28853,49127,1.583328e+07,206138.84,0.00,36.77,5.696066e+06,120894.28,1445.08987,536.25142,774.63730,1163.22075,0.40,461318.6,215943,170647,34566,8190,2540,431886
4,2014-07-01,1835144.66,114323,29287,48528,1.925414e+07,155870.07,300231.00,644.80,7.271089e+06,60804.87,1559.18983,786.14218,911.41471,1335.39708,0.01,486872.6,254348,201533,37542,12322,2951,508696
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,2025-09-01,3892811.47,156706,35396,54928,8.781352e+08,248922.88,353990.51,4995478.81,5.824206e+08,4444577.04,1259.06857,948.59660,974.53909,464.10337,0.48,1074352.8,243393,183162,47337,10107,2787,486786
139,2025-10-01,3906633.17,158600,36032,54526,2.600877e+08,4833965.89,1845913.56,40506.05,3.993856e+07,6033857.29,1340.00342,947.33806,1040.15079,479.55698,0.09,1107951.1,247770,184841,50635,10160,2134,495540
140,2025-11-01,3917134.22,160270,35705,54036,1.042772e+09,143391.73,180106.13,22984.50,2.450926e+07,18664097.40,1298.53131,812.54500,918.23883,438.35117,0.18,1084709.5,219058,164868,43263,9601,1326,438116
141,2025-12-01,3929314.11,163044,36253,57662,2.507515e+08,22815.14,698677.01,18367.82,2.041848e+07,2158827.08,1005.39987,856.40874,706.36965,378.81819,0.33,1085129.6,184474,139947,38103,5723,701,368948
142,2026-01-01,3944742.89,160982,35690,55570,2.489311e+08,52556.79,15216.61,4396988.30,1.895500e+07,8361964.22,1273.83386,714.21230,664.70118,439.27299,0.33,1023703.2,163606,124193,30782,6811,1820,327212

In [38]:
df_final.shape

(143, 23)

In [39]:
df_final = df_final.merge(df_ipea_cambio, on='Date').copy()
df_final

,Date,custo_projeto_m2,operacoes_credito_industria_construcao,operacoes_credito_industria_infraestrutura,operacoes_credito_industria_metalurgia_siderurgia,Outra,km,kva,kw,m2,m3,3.24 Metalurgia,3.28 Fabricação de máquinas e equipamentos,"3.29 Fabricação de veículos automotores, reboques e carrocerias","3.30 Fabricação de outros equipamentos de transporte, exceto veículos automotores",IPCA,PIB_mensal,AUTOVEÍCULOS TOTAL_Produção,AUTOMÓVEIS_Produção,COMERCIAIS LEVES_Produção,CAMINHÕES_Produção,ÔNIBUS_Produção,producao_total,valor_cambio_reais
0,2014-03-01,1789677.76,110130,27467,49832,1.281451e+08,27611.11,500.00,51050.17,3.876616e+06,341809.82,1627.26879,648.56838,932.29050,1289.01576,0.92,477202.9,272754,218999,36211,13844,3700,545508,1.425303
1,2014-04-01,1795689.30,111799,27566,49751,2.380034e+06,63868.05,0.00,56000.00,5.135527e+06,30289.10,1568.60663,601.80655,958.02687,1329.35659,0.67,479729.8,277091,218831,42551,12314,3395,554182,1.488117
2,2014-05-01,1809898.74,113783,28389,49331,2.394161e+06,79957.55,0.00,0.00,5.659767e+06,308819.95,1598.92700,660.43780,967.89891,1304.52774,0.46,481273.4,281355,225128,40144,12695,3388,562710,1.504061
3,2014-06-01,1822703.31,114449,28853,49127,1.583328e+07,206138.84,0.00,36.77,5.696066e+06,120894.28,1445.08987,536.25142,774.63730,1163.22075,0.40,461318.6,215943,170647,34566,8190,2540,431886,1.489907
4,2014-07-01,1835144.66,114323,29287,48528,1.925414e+07,155870.07,300231.00,644.80,7.271089e+06,60804.87,1559.18983,786.14218,911.41471,1335.39708,0.01,486872.6,254348,201533,37542,12322,2951,508696,1.650081
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,2025-09-01,3892811.47,156706,35396,54928,8.781352e+08,248922.88,353990.51,4995478.81,5.824206e+08,4444577.04,1259.06857,948.59660,974.53909,464.10337,0.48,1074352.8,243393,183162,47337,10107,2787,486786,5.366809
139,2025-10-01,3906633.17,158600,36032,54526,2.600877e+08,4833965.89,1845913.56,40506.05,3.993856e+07,6033857.29,1340.00342,947.33806,1040.15079,479.55698,0.09,1107951.1,247770,184841,50635,10160,2134,495540,5.384926
140,2025-11-01,3917134.22,160270,35705,54036,1.042772e+09,143391.73,180106.13,22984.50,2.450926e+07,18664097.40,1298.53131,812.54500,918.23883,438.35117,0.18,1084709.5,219058,164868,43263,9601,1326,438116,5.340253
141,2025-12-01,3929314.11,163044,36253,57662,2.507515e+08,22815.14,698677.01,18367.82,2.041848e+07,2158827.08,1005.39987,856.40874,706.36965,378.81819,0.33,1085129.6,184474,139947,38103,5723,701,368948,5.452482
142,2026-01-01,3944742.89,160982,35690,55570,2.489311e+08,52556.79,15216.61,4396988.30,1.895500e+07,8361964.22,1273.83386,714.21230,664.70118,439.27299,0.33,1023703.2,163606,124193,30782,6811,1820,327212,5.337419

In [40]:
#df_final = df_final.merge(df_ipea_fbc, on='Date').copy()
#df_final

In [41]:
df_final = df_final.merge(df_sidra_ipp, on='Date').copy()
df_final

,Date,custo_projeto_m2,operacoes_credito_industria_construcao,operacoes_credito_industria_infraestrutura,operacoes_credito_industria_metalurgia_siderurgia,Outra,km,kva,kw,m2,m3,3.24 Metalurgia,3.28 Fabricação de máquinas e equipamentos,"3.29 Fabricação de veículos automotores, reboques e carrocerias","3.30 Fabricação de outros equipamentos de transporte, exceto veículos automotores",IPCA,PIB_mensal,AUTOVEÍCULOS TOTAL_Produção,AUTOMÓVEIS_Produção,COMERCIAIS LEVES_Produção,CAMINHÕES_Produção,ÔNIBUS_Produção,producao_total,valor_cambio_reais,24 METALURGIA,"25 FABRICAÇÃO DE PRODUTOS DE METAL, EXCETO MÁQUINAS E EQUIPAMENTOS","27 FABRICAÇÃO DE MÁQUINAS, APARELHOS E MATERIAIS ELÉTRICOS",28 FABRICAÇÃO DE MÁQUINAS E EQUIPAMENTOS,"29 FABRICAÇÃO DE VEÍCULOS AUTOMOTORES, REBOQUES E CARROCERIAS","30 FABRICAÇÃO DE OUTROS EQUIPAMENTOS DE TRANSPORTE, EXCETO VEÍCULOS AUTOMOTORES"
0,2014-03-01,1789677.76,110130,27467,49832,1.281451e+08,27611.11,500.00,51050.17,3.876616e+06,341809.82,1627.26879,648.56838,932.29050,1289.01576,0.92,477202.9,272754,218999,36211,13844,3700,545508,1.425303,70.78954,77.04495,75.58447,81.12523,77.39578,63.57421
1,2014-04-01,1795689.30,111799,27566,49751,2.380034e+06,63868.05,0.00,56000.00,5.135527e+06,30289.10,1568.60663,601.80655,958.02687,1329.35659,0.67,479729.8,277091,218831,42551,12314,3395,554182,1.488117,70.52026,77.34009,75.14999,80.78319,77.59273,61.84009
2,2014-05-01,1809898.74,113783,28389,49331,2.394161e+06,79957.55,0.00,0.00,5.659767e+06,308819.95,1598.92700,660.43780,967.89891,1304.52774,0.46,481273.4,281355,225128,40144,12695,3388,562710,1.504061,70.72374,77.24797,77.04906,80.80671,77.61381,61.80048
3,2014-06-01,1822703.31,114449,28853,49127,1.583328e+07,206138.84,0.00,36.77,5.696066e+06,120894.28,1445.08987,536.25142,774.63730,1163.22075,0.40,461318.6,215943,170647,34566,8190,2540,431886,1.489907,71.51497,77.06881,76.65715,81.08439,77.66284,62.19166
4,2014-07-01,1835144.66,114323,29287,48528,1.925414e+07,155870.07,300231.00,644.80,7.271089e+06,60804.87,1559.18983,786.14218,911.41471,1335.39708,0.01,486872.6,254348,201533,37542,12322,2951,508696,1.650081,71.32037,76.83444,76.52759,81.05502,77.83338,62.11506
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,2025-09-01,3892811.47,156706,35396,54928,8.781352e+08,248922.88,353990.51,4995478.81,5.824206e+08,4444577.04,1259.06857,948.59660,974.53909,464.10337,0.48,1074352.8,243393,183162,47337,10107,2787,486786,5.366809,170.35175,168.22590,168.92221,183.78253,159.99832,166.67084
139,2025-10-01,3906633.17,158600,36032,54526,2.600877e+08,4833965.89,1845913.56,40506.05,3.993856e+07,6033857.29,1340.00342,947.33806,1040.15079,479.55698,0.09,1107951.1,247770,184841,50635,10160,2134,495540,5.384926,173.44078,167.95270,169.73408,184.22017,160.12022,167.94769
140,2025-11-01,3917134.22,160270,35705,54036,1.042772e+09,143391.73,180106.13,22984.50,2.450926e+07,18664097.40,1298.53131,812.54500,918.23883,438.35117,0.18,1084709.5,219058,164868,43263,9601,1326,438116,5.340253,172.85646,168.44572,172.32235,183.32387,160.50728,167.84633
141,2025-12-01,3929314.11,163044,36253,57662,2.507515e+08,22815.14,698677.01,18367.82,2.041848e+07,2158827.08,1005.39987,856.40874,706.36965,378.81819,0.33,1085129.6,184474,139947,38103,5723,701,368948,5.452482,176.73024,168.95391,175.63531,181.80880,161.10558,170.77303
142,2026-01-01,3944742.89,160982,35690,55570,2.489311e+08,52556.79,15216.61,4396988.30,1.895500e+07,8361964.22,1273.83386,714.21230,664.70118,439.27299,0.33,1023703.2,163606,124193,30782,6811,1820,327212,5.337419,181.55805,171.55540,175.87805,182.11315,161.49538,170.09721

In [42]:
df_final = df_final.merge(df_pnad_ocupacao, on='Date').copy()
df_final

,Date,custo_projeto_m2,operacoes_credito_industria_construcao,operacoes_credito_industria_infraestrutura,operacoes_credito_industria_metalurgia_siderurgia,Outra,km,kva,kw,m2,m3,3.24 Metalurgia,3.28 Fabricação de máquinas e equipamentos,"3.29 Fabricação de veículos automotores, reboques e carrocerias","3.30 Fabricação de outros equipamentos de transporte, exceto veículos automotores",IPCA,PIB_mensal,AUTOVEÍCULOS TOTAL_Produção,AUTOMÓVEIS_Produção,COMERCIAIS LEVES_Produção,CAMINHÕES_Produção,ÔNIBUS_Produção,producao_total,valor_cambio_reais,24 METALURGIA,"25 FABRICAÇÃO DE PRODUTOS DE METAL, EXCETO MÁQUINAS E EQUIPAMENTOS","27 FABRICAÇÃO DE MÁQUINAS, APARELHOS E MATERIAIS ELÉTRICOS",28 FABRICAÇÃO DE MÁQUINAS E EQUIPAMENTOS,"29 FABRICAÇÃO DE VEÍCULOS AUTOMOTORES, REBOQUES E CARROCERIAS","30 FABRICAÇÃO DE OUTROS EQUIPAMENTOS DE TRANSPORTE, EXCETO VEÍCULOS AUTOMOTORES","Nível da ocupação, na semana de referência, das pessoas de 14 anos ou mais de idade"
0,2014-03-01,1789677.76,110130,27467,49832,1.281451e+08,27611.11,500.00,51050.17,3.876616e+06,341809.82,1627.26879,648.56838,932.29050,1289.01576,0.92,477202.9,272754,218999,36211,13844,3700,545508,1.425303,70.78954,77.04495,75.58447,81.12523,77.39578,63.57421,57.8
1,2014-04-01,1795689.30,111799,27566,49751,2.380034e+06,63868.05,0.00,56000.00,5.135527e+06,30289.10,1568.60663,601.80655,958.02687,1329.35659,0.67,479729.8,277091,218831,42551,12314,3395,554182,1.488117,70.52026,77.34009,75.14999,80.78319,77.59273,61.84009,57.9
2,2014-05-01,1809898.74,113783,28389,49331,2.394161e+06,79957.55,0.00,0.00,5.659767e+06,308819.95,1598.92700,660.43780,967.89891,1304.52774,0.46,481273.4,281355,225128,40144,12695,3388,562710,1.504061,70.72374,77.24797,77.04906,80.80671,77.61381,61.80048,58.0
3,2014-06-01,1822703.31,114449,28853,49127,1.583328e+07,206138.84,0.00,36.77,5.696066e+06,120894.28,1445.08987,536.25142,774.63730,1163.22075,0.40,461318.6,215943,170647,34566,8190,2540,431886,1.489907,71.51497,77.06881,76.65715,81.08439,77.66284,62.19166,58.1
4,2014-07-01,1835144.66,114323,29287,48528,1.925414e+07,155870.07,300231.00,644.80,7.271089e+06,60804.87,1559.18983,786.14218,911.41471,1335.39708,0.01,486872.6,254348,201533,37542,12322,2951,508696,1.650081,71.32037,76.83444,76.52759,81.05502,77.83338,62.11506,58.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,2025-09-01,3892811.47,156706,35396,54928,8.781352e+08,248922.88,353990.51,4995478.81,5.824206e+08,4444577.04,1259.06857,948.59660,974.53909,464.10337,0.48,1074352.8,243393,183162,47337,10107,2787,486786,5.366809,170.35175,168.22590,168.92221,183.78253,159.99832,166.67084,58.7
139,2025-10-01,3906633.17,158600,36032,54526,2.600877e+08,4833965.89,1845913.56,40506.05,3.993856e+07,6033857.29,1340.00342,947.33806,1040.15079,479.55698,0.09,1107951.1,247770,184841,50635,10160,2134,495540,5.384926,173.44078,167.95270,169.73408,184.22017,160.12022,167.94769,58.8
140,2025-11-01,3917134.22,160270,35705,54036,1.042772e+09,143391.73,180106.13,22984.50,2.450926e+07,18664097.40,1298.53131,812.54500,918.23883,438.35117,0.18,1084709.5,219058,164868,43263,9601,1326,438116,5.340253,172.85646,168.44572,172.32235,183.32387,160.50728,167.84633,59.0
141,2025-12-01,3929314.11,163044,36253,57662,2.507515e+08,22815.14,698677.01,18367.82,2.041848e+07,2158827.08,1005.39987,856.40874,706.36965,378.81819,0.33,1085129.6,184474,139947,38103,5723,701,368948,5.452482,176.73024,168.95391,175.63531,181.80880,161.10558,170.77303,58.9
142,2026-01-01,3944742.89,160982,35690,55570,2.489311e+08,52556.79,15216.61,4396988.30,1.895500e+07,8361964.22,1273.83386,714.21230,664.70118,439.27299,0.33,1023703.2,163606,124193,30782,6811,1820,327212,5.337419,181.55805,171.55540,175.87805,182.11315,161.49538,170.09721,58.7

In [43]:
df_final = df_final.merge(df_ipea_selic, on='Date').copy()
df_final

,Date,custo_projeto_m2,operacoes_credito_industria_construcao,operacoes_credito_industria_infraestrutura,operacoes_credito_industria_metalurgia_siderurgia,Outra,km,kva,kw,m2,m3,3.24 Metalurgia,3.28 Fabricação de máquinas e equipamentos,"3.29 Fabricação de veículos automotores, reboques e carrocerias","3.30 Fabricação de outros equipamentos de transporte, exceto veículos automotores",IPCA,PIB_mensal,AUTOVEÍCULOS TOTAL_Produção,AUTOMÓVEIS_Produção,COMERCIAIS LEVES_Produção,CAMINHÕES_Produção,ÔNIBUS_Produção,producao_total,valor_cambio_reais,24 METALURGIA,"25 FABRICAÇÃO DE PRODUTOS DE METAL, EXCETO MÁQUINAS E EQUIPAMENTOS","27 FABRICAÇÃO DE MÁQUINAS, APARELHOS E MATERIAIS ELÉTRICOS",28 FABRICAÇÃO DE MÁQUINAS E EQUIPAMENTOS,"29 FABRICAÇÃO DE VEÍCULOS AUTOMOTORES, REBOQUES E CARROCERIAS","30 FABRICAÇÃO DE OUTROS EQUIPAMENTOS DE TRANSPORTE, EXCETO VEÍCULOS AUTOMOTORES","Nível da ocupação, na semana de referência, das pessoas de 14 anos ou mais de idade",taxa_selic_aa
0,2014-03-01,1789677.76,110130,27467,49832,1.281451e+08,27611.11,500.00,51050.17,3.876616e+06,341809.82,1627.26879,648.56838,932.29050,1289.01576,0.92,477202.9,272754,218999,36211,13844,3700,545508,1.425303,70.78954,77.04495,75.58447,81.12523,77.39578,63.57421,57.8,9.641534
1,2014-04-01,1795689.30,111799,27566,49751,2.380034e+06,63868.05,0.00,56000.00,5.135527e+06,30289.10,1568.60663,601.80655,958.02687,1329.35659,0.67,479729.8,277091,218831,42551,12314,3395,554182,1.488117,70.52026,77.34009,75.14999,80.78319,77.59273,61.84009,57.9,10.296141
2,2014-05-01,1809898.74,113783,28389,49331,2.394161e+06,79957.55,0.00,0.00,5.659767e+06,308819.95,1598.92700,660.43780,967.89891,1304.52774,0.46,481273.4,281355,225128,40144,12695,3388,562710,1.504061,70.72374,77.24797,77.04906,80.80671,77.61381,61.80048,58.0,10.954329
3,2014-06-01,1822703.31,114449,28853,49127,1.583328e+07,206138.84,0.00,36.77,5.696066e+06,120894.28,1445.08987,536.25142,774.63730,1163.22075,0.40,461318.6,215943,170647,34566,8190,2540,431886,1.489907,71.51497,77.06881,76.65715,81.08439,77.66284,62.19166,58.1,10.296141
4,2014-07-01,1835144.66,114323,29287,48528,1.925414e+07,155870.07,300231.00,644.80,7.271089e+06,60804.87,1559.18983,786.14218,911.41471,1335.39708,0.01,486872.6,254348,201533,37542,12322,2951,508696,1.650081,71.32037,76.83444,76.52759,81.05502,77.83338,62.11506,58.0,12.014922
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,2025-09-01,3892811.47,156706,35396,54928,8.781352e+08,248922.88,353990.51,4995478.81,5.824206e+08,4444577.04,1259.06857,948.59660,974.53909,464.10337,0.48,1074352.8,243393,183162,47337,10107,2787,486786,5.366809,170.35175,168.22590,168.92221,183.78253,159.99832,166.67084,58.7,15.663411
139,2025-10-01,3906633.17,158600,36032,54526,2.600877e+08,4833965.89,1845913.56,40506.05,3.993856e+07,6033857.29,1340.00342,947.33806,1040.15079,479.55698,0.09,1107951.1,247770,184841,50635,10160,2134,495540,5.384926,173.44078,167.95270,169.73408,184.22017,160.12022,167.94769,58.8,16.488838
140,2025-11-01,3917134.22,160270,35705,54036,1.042772e+09,143391.73,180106.13,22984.50,2.450926e+07,18664097.40,1298.53131,812.54500,918.23883,438.35117,0.18,1084709.5,219058,164868,43263,9601,1326,438116,5.340253,172.85646,168.44572,172.32235,183.32387,160.50728,167.84633,59.0,13.353730
141,2025-12-01,3929314.11,163044,36253,57662,2.507515e+08,22815.14,698677.01,18367.82,2.041848e+07,2158827.08,1005.39987,856.40874,706.36965,378.81819,0.33,1085129.6,184474,139947,38103,5723,701,368948,5.452482,176.73024,168.95391,175.63531,181.80880,161.10558,170.77303,58.9,15.663411
142,2026-01-01,3944742.89,160982,35690,55570,2.489311e+08,52556.79,15216.61,4396988.30,1.895500e+07,8361964.22,1273.83386,714.21230,664.70118,439.27299,0.33,1023703.2,163606,124193,30782,6811,1820,327212,5.337419,181.55805,171.55540,175.87805,182.11315,161.49538,170.09721,58.7,14.843349

In [44]:
df_final.head()

,Date,custo_projeto_m2,operacoes_credito_industria_construcao,operacoes_credito_industria_infraestrutura,operacoes_credito_industria_metalurgia_siderurgia,Outra,km,kva,kw,m2,m3,3.24 Metalurgia,3.28 Fabricação de máquinas e equipamentos,"3.29 Fabricação de veículos automotores, reboques e carrocerias","3.30 Fabricação de outros equipamentos de transporte, exceto veículos automotores",IPCA,PIB_mensal,AUTOVEÍCULOS TOTAL_Produção,AUTOMÓVEIS_Produção,COMERCIAIS LEVES_Produção,CAMINHÕES_Produção,ÔNIBUS_Produção,producao_total,valor_cambio_reais,24 METALURGIA,"25 FABRICAÇÃO DE PRODUTOS DE METAL, EXCETO MÁQUINAS E EQUIPAMENTOS","27 FABRICAÇÃO DE MÁQUINAS, APARELHOS E MATERIAIS ELÉTRICOS",28 FABRICAÇÃO DE MÁQUINAS E EQUIPAMENTOS,"29 FABRICAÇÃO DE VEÍCULOS AUTOMOTORES, REBOQUES E CARROCERIAS","30 FABRICAÇÃO DE OUTROS EQUIPAMENTOS DE TRANSPORTE, EXCETO VEÍCULOS AUTOMOTORES","Nível da ocupação, na semana de referência, das pessoas de 14 anos ou mais de idade",taxa_selic_aa
0,2014-03-01,1789677.76,110130,27467,49832,1.281451e+08,27611.11,500.0,51050.17,3876615.57,341809.82,1627.26879,648.56838,932.29050,1289.01576,0.92,477202.9,272754,218999,36211,13844,3700,545508,1.425303,70.78954,77.04495,75.58447,81.12523,77.39578,63.57421,57.8,9.641534
1,2014-04-01,1795689.30,111799,27566,49751,2.380034e+06,63868.05,0.0,56000.00,5135527.36,30289.10,1568.60663,601.80655,958.02687,1329.35659,0.67,479729.8,277091,218831,42551,12314,3395,554182,1.488117,70.52026,77.34009,75.14999,80.78319,77.59273,61.84009,57.9,10.296141
2,2014-05-01,1809898.74,113783,28389,49331,2.394161e+06,79957.55,0.0,0.00,5659766.78,308819.95,1598.92700,660.43780,967.89891,1304.52774,0.46,481273.4,281355,225128,40144,12695,3388,562710,1.504061,70.72374,77.24797,77.04906,80.80671,77.61381,61.80048,58.0,10.954329
3,2014-06-01,1822703.31,114449,28853,49127,1.583328e+07,206138.84,0.0,36.77,5696065.83,120894.28,1445.08987,536.25142,774.63730,1163.22075,0.40,461318.6,215943,170647,34566,8190,2540,431886,1.489907,71.51497,77.06881,76.65715,81.08439,77.66284,62.19166,58.1,10.296141
4,2014-07-01,1835144.66,114323,29287,48528,1.925414e+07,155870.07,300231.0,644.80,7271088.73,60804.87,1559.18983,786.14218,911.41471,1335.39708,0.01,486872.6,254348,201533,37542,12322,2951,508696,1.650081,71.32037,76.83444,76.52759,81.05502,77.83338,62.11506,58.0,12.014922

In [45]:
df_final.shape

(143, 32)

# Variável Alvo

In [46]:
df_variavel_alvo = pd.read_excel(caminho_principal+arquivo_variavel_alvo, engine='openpyxl')

In [47]:
df_variavel_alvo.head()

,Categoria,Especificação,Data,Valor
0,Consumo Aparente / Apparent Consumption (***),Consumo Aparente / Apparent Consumption (***),2013-01-01,2167.705
1,Consumo Aparente / Apparent Consumption (***),Consumo Aparente / Apparent Consumption (***),2013-02-01,2069.840
2,Consumo Aparente / Apparent Consumption (***),Consumo Aparente / Apparent Consumption (***),2013-03-01,2330.914
3,Consumo Aparente / Apparent Consumption (***),Consumo Aparente / Apparent Consumption (***),2013-04-01,2402.633
4,Consumo Aparente / Apparent Consumption (***),Consumo Aparente / Apparent Consumption (***),2013-05-01,2456.820

In [48]:
df_consumo_aparente = df_variavel_alvo[(df_variavel_alvo['Categoria'] == 'Consumo Aparente / Apparent Consumption (***)') & 
                                        (df_variavel_alvo['Especificação'] == 'Longos / Long Products\n(Inclui Blocos e Tarugos / Included Ingots, Blooms and Billets)')].copy()
df_consumo_aparente.reset_index(drop=True, inplace=True)
df_consumo_aparente.rename(columns={'Valor':'Consumo Aparente', 'Data':'Date'}, inplace=True)
df_consumo_aparente.drop(['Categoria', 'Especificação'], axis=1, inplace=True)

In [49]:
df_consumo_aparente.head()

        Date  Consumo Aparente
0 2013-01-01           905.896
1 2013-02-01           874.438
2 2013-03-01          1018.972
3 2013-04-01          1035.119
4 2013-05-01          1053.642

In [50]:
df_consumo_aparente.shape

(157, 2)

# Gerar dataframe com demais variáveis

In [51]:
df = df_consumo_aparente.copy()
for arquivo in lista_arquivos:
    if '.xlsx' in arquivo:
        print(f'Abrindo: {arquivo}...')
        df_temp = pd.read_excel(caminho_principal+arquivo, engine='openpyxl')
        df = df.merge(df_temp, on='Date').copy()
        print(f'-> {arquivo} incluído na tabela mestre!\n')
        #print(f"Data mínima: {df_temp['Date'].min()}")
        #print(f"Data máxima: {df_temp['Date'].max()}")
        print('\n')

Abrindo: anfavea_producao_veiculos.xlsx...
-> anfavea_producao_veiculos.xlsx incluído na tabela mestre!



Abrindo: bc_sgs_ipca_pib.xlsx...
-> bc_sgs_ipca_pib.xlsx incluído na tabela mestre!



Abrindo: bc_sgs_operacoes_credito_industria.xlsx...
-> bc_sgs_operacoes_credito_industria.xlsx incluído na tabela mestre!



Abrindo: gov_br_cno.xlsx...
-> gov_br_cno.xlsx incluído na tabela mestre!



Abrindo: ipea_cambio.xlsx...
-> ipea_cambio.xlsx incluído na tabela mestre!



Abrindo: ipea_selic.xlsx...
-> ipea_selic.xlsx incluído na tabela mestre!



Abrindo: sidra_ipp.xlsx...
-> sidra_ipp.xlsx incluído na tabela mestre!



Abrindo: sidra_pim_pf.xlsx...
-> sidra_pim_pf.xlsx incluído na tabela mestre!



Abrindo: sidra_pnad_ocupacao.xlsx...
-> sidra_pnad_ocupacao.xlsx incluído na tabela mestre!



Abrindo: sidra_sinapi_m2.xlsx...
-> sidra_sinapi_m2.xlsx incluído na tabela mestre!

# Juntar a variável alvo à tabela mestre

In [52]:
#df_tabela_mestre = df.merge(df_consumo_aparente, on='Date').copy()
df_tabela_mestre = df.copy()

In [53]:
df_tabela_mestre

,Date,Consumo Aparente,AUTOVEÍCULOS TOTAL_Produção,AUTOMÓVEIS_Produção,COMERCIAIS LEVES_Produção,CAMINHÕES_Produção,ÔNIBUS_Produção,producao_total,IPCA,PIB_mensal,operacoes_credito_industria_construcao,operacoes_credito_industria_infraestrutura,operacoes_credito_industria_metalurgia_siderurgia,Outra,km,kva,kw,m2,m3,valor_cambio_reais,taxa_selic_aa,24 METALURGIA,"25 FABRICAÇÃO DE PRODUTOS DE METAL, EXCETO MÁQUINAS E EQUIPAMENTOS","27 FABRICAÇÃO DE MÁQUINAS, APARELHOS E MATERIAIS ELÉTRICOS",28 FABRICAÇÃO DE MÁQUINAS E EQUIPAMENTOS,"29 FABRICAÇÃO DE VEÍCULOS AUTOMOTORES, REBOQUES E CARROCERIAS","30 FABRICAÇÃO DE OUTROS EQUIPAMENTOS DE TRANSPORTE, EXCETO VEÍCULOS AUTOMOTORES",3.24 Metalurgia,3.28 Fabricação de máquinas e equipamentos,"3.29 Fabricação de veículos automotores, reboques e carrocerias","3.30 Fabricação de outros equipamentos de transporte, exceto veículos automotores","Nível da ocupação, na semana de referência, das pessoas de 14 anos ou mais de idade",custo_projeto_m2
0,2014-03-01,940.044,272754,218999,36211,13844,3700,545508,0.92,477202.9,110130,27467,49832,1.281451e+08,27611.11,500.00,51050.17,3.876616e+06,341809.82,1.425303,9.641534,70.78954,77.04495,75.58447,81.12523,77.39578,63.57421,1627.26879,648.56838,932.29050,1289.01576,57.8,1789677.76
1,2014-04-01,951.105,277091,218831,42551,12314,3395,554182,0.67,479729.8,111799,27566,49751,2.380034e+06,63868.05,0.00,56000.00,5.135527e+06,30289.10,1.488117,10.296141,70.52026,77.34009,75.14999,80.78319,77.59273,61.84009,1568.60663,601.80655,958.02687,1329.35659,57.9,1795689.30
2,2014-05-01,981.738,281355,225128,40144,12695,3388,562710,0.46,481273.4,113783,28389,49331,2.394161e+06,79957.55,0.00,0.00,5.659767e+06,308819.95,1.504061,10.954329,70.72374,77.24797,77.04906,80.80671,77.61381,61.80048,1598.92700,660.43780,967.89891,1304.52774,58.0,1809898.74
3,2014-06-01,852.989,215943,170647,34566,8190,2540,431886,0.40,461318.6,114449,28853,49127,1.583328e+07,206138.84,0.00,36.77,5.696066e+06,120894.28,1.489907,10.296141,71.51497,77.06881,76.65715,81.08439,77.66284,62.19166,1445.08987,536.25142,774.63730,1163.22075,58.1,1822703.31
4,2014-07-01,974.740,254348,201533,37542,12322,2951,508696,0.01,486872.6,114323,29287,48528,1.925414e+07,155870.07,300231.00,644.80,7.271089e+06,60804.87,1.650081,12.014922,71.32037,76.83444,76.52759,81.05502,77.83338,62.11506,1559.18983,786.14218,911.41471,1335.39708,58.0,1835144.66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,2025-09-01,906.062,243393,183162,47337,10107,2787,486786,0.48,1074352.8,156706,35396,54928,8.781352e+08,248922.88,353990.51,4995478.81,5.824206e+08,4444577.04,5.366809,15.663411,170.35175,168.22590,168.92221,183.78253,159.99832,166.67084,1259.06857,948.59660,974.53909,464.10337,58.7,3892811.47
139,2025-10-01,907.294,247770,184841,50635,10160,2134,495540,0.09,1107951.1,158600,36032,54526,2.600877e+08,4833965.89,1845913.56,40506.05,3.993856e+07,6033857.29,5.384926,16.488838,173.44078,167.95270,169.73408,184.22017,160.12022,167.94769,1340.00342,947.33806,1040.15079,479.55698,58.8,3906633.17
140,2025-11-01,788.157,219058,164868,43263,9601,1326,438116,0.18,1084709.5,160270,35705,54036,1.042772e+09,143391.73,180106.13,22984.50,2.450926e+07,18664097.40,5.340253,13.353730,172.85646,168.44572,172.32235,183.32387,160.50728,167.84633,1298.53131,812.54500,918.23883,438.35117,59.0,3917134.22
141,2025-12-01,681.715,184474,139947,38103,5723,701,368948,0.33,1085129.6,163044,36253,57662,2.507515e+08,22815.14,698677.01,18367.82,2.041848e+07,2158827.08,5.452482,15.663411,176.73024,168.95391,175.63531,181.80880,161.10558,170.77303,1005.39987,856.40874,706.36965,378.81819,58.9,3929314.11
142,2026-01-01,736.387,163606,124193,30782,6811,1820,327212,0.33,1023703.2,160982,35690,55570,2.489311e+08,52556.79,15216.61,4396988.30,1.895500e+07,8361964.22,5.337419,14.843349,181.55805,171.55540,175.87805,182.11315,161.49538,170.09721,1273.83386,714.21230,664.70118,439.27299,58.7,3944742.89

In [54]:
df_tabela_mestre.shape

(143, 33)

In [55]:
df_tabela_mestre.to_excel('./dados/gold/tabela_mestre.xlsx', index=False, engine='openpyxl')